export const Icons = {
  BGImage: require('../assets/images/bgImage.png'),
  graphIcon: require('../assets/images/graph.png'),
  cryptoIcon: require('../assets/images/crypto.png'),
  timerIcon: require('../assets/images/timer.png'),
  backIcon: require('../assets/images/left.png'),
  shareIcon: require('../assets/images/share.png'),
  starIcon: require('../assets/images/star.png'),
  placeholder: require('../assets/images/icon.png'),
  cancelIcon: require('../assets/images/cancel.png'),
  supportIcon: require('../assets/images/support.png'),
  imageIcon: require('../assets/images/imageIcon.png'),
  attachment: require('../assets/images/attachment.png'),
  clockIcon: require('../assets/images/clockIcon.png'),
  coinBroken: require('../assets/images/coinBroken.png'),
  switch: require('../assets/images/switch.png'),
  arrow: require('../assets/images/arrow.png'),
  setting: require('../assets/images/setting.png'),
  editIcon: require('../assets/images/editIcon.png'),
};
